version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=sanctity
      - DB_USER=postgres
      - DB_PASSWORD=postgres@123
      - DB_HOST=db

    command: >
     sh -c "python manage.py makemigrations &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sanctity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
